### ISSUE TITLE
melpa

### ISSUE THREAD

**Issue by laalsaas** [Ziqi-Yang/typst-mode.el#4]
hey, I really like the fact that there is a typst mode for emacs so fast. I just wanted to ask you if you plan to publish typst-mode.el on melpa, and if not, encourage you to do so.

keep up the awesome work

**Comment by Ziqi-Yang** [comment]
Hi, laalsaas.
Thank you for your kind words and interest in `typst-mode`! I'm glad to hear that you're enjoying it and finding it useful. Frankly speaking, I haven't considered publish it to Melpa before since I use `straight` to manage my packages and it is quite easy to pull packages from a git repo. However, I appreciate your advice to publish it on the Melpa, since there are many emacs users who prefer to use Melpa as their package source. I will look into the process of publishing the package on Melpa later. Once I have done this, I will close the issue. Thank you for your support and encouragement. If you have any other suggestions or feedback, please don't hesitate to share.

**Comment by Ziqi-Yang** [comment]
Merged into Melpa :)
